### ISSUE TITLE
remove this obsolete app from apps.nextcloud.com please

### ISSUE THREAD

**Issue by p-bo** [LukasReschke/githubmergetracker#11]
Hello,
would it be possible to follow instructions on:

https://nextcloudappstore.readthedocs.io/en/latest/restapi.html#delete-an-app

and remove your past app:

https://apps.nextcloud.com/apps/githubmergetracker

and help through this to tidy up the Nextcloud App store (most importantly it clutters apps catalogue in every Nextcloud instance) a bit please?

Thanks and have a nice day

**Comment by ChristophWurst** [comment]
Fair enough

**Comment by ChristophWurst** [comment]
```json
{"detail":"You do not have permission to perform this action."}
```

**Comment by p-bo** [comment]
(sorry, didn'ŧ even notice, that I was redirected from original Report problem link from app store to your account on Github)

It seems, that there were not done app ownership transfer - see

https://nextcloudappstore.readthedocs.io/en/latest/developer.html?highlight=ownership#transferring-your-app-to-a-new-owner

and app is thus still owned by Lukas Reshke, as stated  on app page.

So, @LukasReschke may we ask you for help there (make deletion or transfer ownership to Christoph to be able to do it) please?

Thanks

**Comment by LukasReschke** [comment]
Anyone with admin privileges on apps.nextcloud.com should be able to reassign ownership of this app or delete it directly.

I don't have this kind of access anymore.

**Comment by p-bo** [comment]
@LukasReschke
I thought the same, hence already created this topic on forum:
https://help.nextcloud.com/t/apps-nextcloud-com-and-applications-section-on-every-nc-instance-how-to-remove-abandonware/150801

**Comment by ChristophWurst** [comment]
It has been taken off the app store.
